### ISSUE TITLE
Add side padding and fix typo

### ISSUE THREAD

**Issue by tigeranniemac** [GABeckemeier/Cat_Costume_Project#1]
https://github.com/GABeckemeier/Cat_Costume_Project/blob/91a2835bcdea4d0c9b2f14b2ec02b7a6cd4359b1/assets/css/index.css#L51-L53

Add side padding to the `<nav>` parent so the `h1` doesn't push up against the side of browser. The `height; 80px;` is a typo so it actually isn't rendering.

**Comment by GABeckemeier** [comment]
I added padding: 0 80px; and deleted height: 80px; since it literally did nothing. Then realized that em would probs be a better way to express a relative measurement so made padding: 0 2em; instead. This will be reflected in my next push!
