### ISSUE TITLE
Change max-width size

### ISSUE THREAD

**Issue by tigeranniemac** [GABeckemeier/Cat_Costume_Project#2]
https://github.com/GABeckemeier/Cat_Costume_Project/blob/91a2835bcdea4d0c9b2f14b2ec02b7a6cd4359b1/assets/css/index.css#L7

On my laptop the page scrolls horizontally because it's too small to fit 1515px max-width. Try what you use for the mobile version.

**Comment by GABeckemeier** [comment]
I changed the specs on the #headcat picture id to be hella more responsive off of the specs for the #map image. Horizontal scrolling due to a rigid max-width should be no more!
