### ISSUE TITLE
These boxes stack on my laptop

### ISSUE THREAD

**Issue by tigeranniemac** [GABeckemeier/Cat_Costume_Project#3]
https://github.com/GABeckemeier/Cat_Costume_Project/blob/91a2835bcdea4d0c9b2f14b2ec02b7a6cd4359b1/assets/css/index.css#L69-L75

These should be side by side. Maybe use the same technique you use for the cats!

**Comment by GABeckemeier** [comment]
Fixed all known box stack issues using flexbox technique (I love flexbox).
