### ISSUE TITLE
Remove margin on h1 and footer height sizing

### ISSUE THREAD

**Issue by tigeranniemac** [GABeckemeier/Cat_Costume_Project#5]
https://github.com/GABeckemeier/Cat_Costume_Project/blob/91a2835bcdea4d0c9b2f14b2ec02b7a6cd4359b1/assets/css/index.css#L104-L112

There is a white area above and below the footer, that's because of the built-in margin.

Height:125px isn't working as you'd think, but it along with padding-top accomplishes the feat. If in the future you have to add in social icons, this solve wouldn't work. Try to put padding on the parent `<footer>` tag like you do in the boxes. This would also help with the padding in mobile version.

**Comment by GABeckemeier** [comment]
Excess white space is now off of the footer (adding <footer> specs and cleaning up footer h1 specs seemed to do the trick!)
