### ISSUE TITLE
INLINE STYLE

### ISSUE THREAD

**Issue by tigeranniemac** [GABeckemeier/Cat_Costume_Project#6]
https://github.com/GABeckemeier/Cat_Costume_Project/blob/91a2835bcdea4d0c9b2f14b2ec02b7a6cd4359b1/index.html#L69

Please remove inline style and use CSS!

**Comment by GABeckemeier** [comment]
Turns out that width setting is not needed (at all) so I deleted it off the <img> and everything looks good to go now. Thank you for your time!
